[theme]
primaryColor = "#BF9B30"
backgroundColor = "#0F1117"
secondaryBackgroundColor = "#1A1D23"
textColor = "#E0E0E0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
