[theme]
primaryColor = "#BF9B30"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F0"
textColor = "#1E1E1E"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
